apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-for-backend
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - bindings:
        - ref: backend-trigger-binding
      template:
        ref: backend-trigger-template
