apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: backend-trigger-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: backend-pipeline-run-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: backend-pipeline
        workspaces:
          - name: pipeline-shared-data
            persistentVolumeClaim:
              claimName: backend-pvc
          - name: git-basic-auth
            secret:
              secretName: git-credentials
