apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: nodejs
  name: backend-pipeline
spec:
  workspaces:
    - name: pipeline-shared-data
      description: |
        This workspace stores the cloned repository and is available to all steps
    - name: git-basic-auth

  params:
    - name: image-repo
      type: string
      description: Docker image name
      default: quay.io/shinnosuke_yoshizawa_ibm/checkride-be
      # default: quay.io/shinnosuke_yoshizawa_ibm/express-sample-app
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: https://github.com/shxn0/checkride-be.git
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-shared-data
        - name: basic-auth
          workspace: git-basic-auth

    # ここから追記
    # - name: install-dependencies
    #   runAfter:
    #     - clone-repository
    #   taskRef:
    #     name: npm
    #   workspaces:
    #     - name: source
    #       workspace: pipeline-shared-data
    #   params:
    #     - name: ARGS
    #       value:
    #         - clean-install

    # - name: run-tests
    #   runAfter:
    #     - install-dependencies
    #   taskRef:
    #     name: npm
    #   workspaces:
    #     - name: source
    #       workspace: pipeline-shared-data
    #   params:
    #     - name: ARGS
    #       value:
    #         - test

    - name: build-image
      # runAfter:
      #   - run-tests
      runAfter:
        - clone-repository
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: IMAGE
          # value: "$(params.image-repo):latest"
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"

    - name: kustomize-build
      runAfter:
        - build-image
      params:
        - name: image-with-tag
          value: "quay.io/shinnosuke_yoshizawa_ibm/checkride-be=$(params.image-repo):$(tasks.clone-repository.results.commit)"
          # value: "quay.io/shinnosuke_yoshizawa_ibm/checkride-be=$(params.image-repo):latest"
          # value: "quay.io/shinnosuke_yoshizawa_ibm/express-sample-app=$(params.image-repo):$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: Task
        name: kustomize-build
      workspaces:
        - name: source
          workspace: pipeline-shared-data

    - name: test-deploy
      runAfter:
        - kustomize-build
      params:
        - name: app-namespace
          value: shinnosuke-yoshizawa-checkride
        - name: app-name
          value: shinnosuke-yoshizawa-checkride
      taskRef:
        kind: Task
        name: test-deploy
      workspaces:
        - name: source
          workspace: pipeline-shared-data
